const WHATSAPP_NUMBER=''; // Telefon numarası geldiğinde 905xxxxxxxxx formatında buraya yazılacak.
let trip='one', payment='Nakit', selectedVehicle='VIP Private — 1-7 kişi', mapTarget=null, map=null, marker=null, pickedLatLng=null;
const dict={
tr:{navTransfer:'Transfer',navFleet:'Araçlar',navCampaign:'Kampanyalar',navContact:'İletişim',heroTitle:"Antalya'da <span class='gold'>konforlu</span> ve güvenli VIP transfer",heroText:"Antalya Havalimanı ve Gazipaşa-Alanya Havalimanı'ndan Antalya'nın ilçelerine özel araç transferi. Gidiş-dönüş rezervasyonunuzu kolayca oluşturun.",bookingTitle:'Transfer talebi oluştur',oneWay:'Tek Yön',roundTrip:'Gidiş - Dönüş',airportLabel:'Havalimanı',fromLabel:'Alınış yeri',toLabel:'Gidilecek yer',passengerLabel:'Yolcu',dateLabel:'Gidiş tarihi',timeLabel:'Gidiş saati',returnDate:'Dönüş tarihi',returnTime:'Dönüş saati',flightLabel:'Uçuş numarası',search:'Teklif Al · Transfer seçeneklerini göster',whyTitle:'Neden bizi tercih etmelisiniz?',whyText:'Havalimanından otelinize veya belirlediğiniz adrese özel, konforlu ve zamanında ulaşım.',f1:'Uçuş takibi',f1p:'Uçuş bilgileriniz rezervasyon akışına eklenebilir.',f2:'Özel araç',f2p:'Paylaşımlı değil, sadece size özel transfer.',f3:'Kolay ödeme',f3p:'Kredi kartı veya nakit ödeme tercihi.',f4:'4 dil',f4p:'Türkçe, İngilizce, Rusça ve Almanca.',fleetTitle:'Araç filomuz',fleetText:'Yolcu sayınıza göre aracınızı seçin. Gerçek araç fotoğrafları daha sonra eklenebilir.',campaignTitle:'Kampanyaları kaçırmayın',campaignText:'Yeni müşteri, gidiş-dönüş ve dönemsel kampanyalar burada yayınlanabilir.',book:'Teklif Al',contactTitle:'İletişim',contactText:'Telefon, WhatsApp, Instagram ve Facebook bilgileri hazır olduğunda bu alan güncellenecek.',modalTitle:'Transfer seçenekleri',confirm:"Teklif talebini WhatsApp'a gönder"},
en:{navTransfer:'Transfer',navFleet:'Vehicles',navCampaign:'Offers',navContact:'Contact',heroTitle:"Comfortable and safe <span class='gold'>VIP transfer</span> in Antalya",heroText:'Private transfers from Antalya Airport and Gazipaşa-Alanya Airport to destinations across Antalya.',bookingTitle:'Create transfer request',oneWay:'One Way',roundTrip:'Round Trip',airportLabel:'Airport',fromLabel:'Pickup',toLabel:'Destination',passengerLabel:'Passengers',dateLabel:'Departure date',timeLabel:'Departure time',returnDate:'Return date',returnTime:'Return time',flightLabel:'Flight number',search:'Get a quote · Show transfer options',whyTitle:'Why choose us?',whyText:'Private, comfortable and on-time transportation from the airport to your hotel or address.',f1:'Flight tracking',f1p:'Flight details can be included in the request.',f2:'Private vehicle',f2p:'No shared rides — the vehicle is exclusively yours.',f3:'Easy payment',f3p:'Choose cash or credit card.',f4:'4 languages',f4p:'Turkish, English, Russian and German.',fleetTitle:'Our fleet',fleetText:'Choose a vehicle according to passenger count. Real vehicle photos can be added later.',campaignTitle:'Don’t miss our offers',campaignText:'New-customer, round-trip and seasonal offers can be displayed here.',book:'Get a quote',contactTitle:'Contact',contactText:'Phone, WhatsApp, Instagram and Facebook details will be added when ready.',modalTitle:'Transfer options',confirm:'Send quote request to WhatsApp'},
ru:{navTransfer:'Трансфер',navFleet:'Автомобили',navCampaign:'Акции',navContact:'Контакты',heroTitle:"Комфортный и безопасный <span class='gold'>VIP-трансфер</span> в Анталье",heroText:'Индивидуальные трансферы из аэропортов Антальи и Газипаша-Аланья по регионам Антальи.',bookingTitle:'Создать заявку',oneWay:'В одну сторону',roundTrip:'Туда и обратно',airportLabel:'Аэропорт',fromLabel:'Откуда',toLabel:'Куда',passengerLabel:'Пассажиры',dateLabel:'Дата отправления',timeLabel:'Время',returnDate:'Дата возвращения',returnTime:'Время возвращения',flightLabel:'Номер рейса',search:'Запросить цену · Показать варианты',whyTitle:'Почему мы?',whyText:'Индивидуальный, комфортный и своевременный трансфер.',f1:'Контроль рейса',f1p:'Данные рейса можно добавить в заявку.',f2:'Индивидуальный автомобиль',f2p:'Только для вас.',f3:'Оплата',f3p:'Наличные или карта.',f4:'4 языка',f4p:'Турецкий, английский, русский и немецкий.',fleetTitle:'Наш автопарк',fleetText:'Выберите автомобиль по количеству пассажиров. Фото автомобилей можно добавить позже.',campaignTitle:'Акции',campaignText:'Здесь будут отображаться специальные предложения.',book:'Запросить цену',contactTitle:'Контакты',contactText:'Телефон, WhatsApp, Instagram и Facebook будут добавлены позже.',modalTitle:'Варианты трансфера',confirm:'Отправить заявку в WhatsApp'},
de:{navTransfer:'Transfer',navFleet:'Fahrzeuge',navCampaign:'Angebote',navContact:'Kontakt',heroTitle:"Komfortabler und sicherer <span class='gold'>VIP-Transfer</span> in Antalya",heroText:'Private Transfers vom Flughafen Antalya und Gazipaşa-Alanya zu Zielen in Antalya.',bookingTitle:'Transferanfrage erstellen',oneWay:'Einfache Fahrt',roundTrip:'Hin & Rückfahrt',airportLabel:'Flughafen',fromLabel:'Abholung',toLabel:'Ziel',passengerLabel:'Passagiere',dateLabel:'Abfahrtsdatum',timeLabel:'Abfahrtszeit',returnDate:'Rückfahrtdatum',returnTime:'Rückfahrtszeit',flightLabel:'Flugnummer',search:'Angebot anfordern · Optionen anzeigen',whyTitle:'Warum wir?',whyText:'Privater, komfortabler und pünktlicher Transfer.',f1:'Flugüberwachung',f1p:'Flugdaten können der Anfrage hinzugefügt werden.',f2:'Privates Fahrzeug',f2p:'Keine Sammelfahrt.',f3:'Einfache Zahlung',f3p:'Kreditkarte oder Barzahlung.',f4:'4 Sprachen',f4p:'Türkisch, Englisch, Russisch und Deutsch.',fleetTitle:'Unsere Fahrzeuge',fleetText:'Wählen Sie nach Passagierzahl. Echte Fahrzeugfotos können später ergänzt werden.',campaignTitle:'Angebote',campaignText:'Hier können Sonderangebote veröffentlicht werden.',book:'Angebot anfordern',contactTitle:'Kontakt',contactText:'Telefon, WhatsApp, Instagram und Facebook werden später ergänzt.',modalTitle:'Transferoptionen',confirm:'Anfrage an WhatsApp senden'}};

function applyLang(l){if(!dict[l])l='tr';document.documentElement.lang=l;document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(dict[l][k])e.innerHTML=dict[l][k]});localStorage.setItem('lang',l)}
document.getElementById('lang').addEventListener('change',e=>applyLang(e.target.value));applyLang(localStorage.getItem('lang')||'tr');

document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');trip=b.dataset.trip;document.querySelectorAll('.returnField').forEach(x=>x.style.display=trip==='round'?'block':'none')}));

function locationText(id){const place=document.getElementById(id).value;const address=document.getElementById(id+'Address').value.trim();return address?place+' | '+address:place}
function startReservation(){const date=document.getElementById('date').value;if(!date){alert('Lütfen gidiş tarihini seçin.');return}if(trip==='round'&&!document.getElementById('rdate').value){alert('Lütfen dönüş tarihini seçin.');return}const txt=`${locationText('from')} → ${locationText('to')}<br>${date} ${document.getElementById('time').value||''}${trip==='round'?`<br>Dönüş: ${document.getElementById('rdate').value||'-'} ${document.getElementById('rtime').value||''}`:''}<br>${document.getElementById('passengers').value} yolcu<br>Uçuş: ${document.getElementById('flight').value||'-'}`;document.getElementById('result').innerHTML='<div class="result">'+txt+'</div>';renderVehicleOptions();document.getElementById('modal').classList.add('show')}
function renderVehicleOptions(){const vehicles=[['VIP Private — 1-7 kişi','VIP Private','1–7 kişi'],['Crafter — 7-16 kişi','Crafter','7–16 kişi'],['Sprinter — 7-16 kişi','Sprinter','7–16 kişi'],['Maybach Lüks — 1-7 kişi','Maybach Lüks','1–7 kişi']];document.getElementById('vehicleOptions').innerHTML=vehicles.map(v=>`<div class="vehicleOption ${selectedVehicle===v[0]?'active':''}" onclick="chooseVehicle('${v[0]}')"><strong>${v[1]}</strong><span>${v[2]} · Özel transfer</span><small>Teklif için seç</small></div>`).join('')}
function chooseVehicle(v){selectedVehicle=v;renderVehicleOptions();if(!document.getElementById('modal').classList.contains('show')){document.getElementById('date').scrollIntoView({behavior:'smooth',block:'center'});startReservation()}}
function closeModal(){document.getElementById('modal').classList.remove('show')}
function setPay(el){document.querySelectorAll('.pay').forEach(x=>x.classList.remove('active'));el.classList.add('active');payment=el.textContent}
function openWhatsApp(){if(!WHATSAPP_NUMBER){alert('WhatsApp numarası henüz eklenmedi. Numara geldiğinde app.js içindeki WHATSAPP_NUMBER alanına eklenecek.');return}window.open('https://wa.me/'+WHATSAPP_NUMBER,'_blank')}
function sendReservation(){const name=document.getElementById('name').value.trim()||'Belirtilmedi';const msg=`Yeni VIP transfer teklif talebi%0A%0AAd Soyad: ${encodeURIComponent(name)}%0AAlınış: ${encodeURIComponent(locationText('from'))}%0AVarış: ${encodeURIComponent(locationText('to'))}%0AHavalimanı: ${encodeURIComponent(document.getElementById('airport').value)}%0ATarih: ${encodeURIComponent(document.getElementById('date').value)}%0ASaat: ${encodeURIComponent(document.getElementById('time').value||'-')}%0ADönüş: ${trip==='round'?encodeURIComponent(document.getElementById('rdate').value+' '+(document.getElementById('rtime').value||'')):'Tek yön'}%0AYolcu: ${encodeURIComponent(document.getElementById('passengers').value)}%0AAraç: ${encodeURIComponent(selectedVehicle)}%0AUçuş: ${encodeURIComponent(document.getElementById('flight').value||'-')}%0AÖdeme: ${encodeURIComponent(payment)}%0AE-posta: ${encodeURIComponent(document.getElementById('email').value||'-')}%0ATelefon: ${encodeURIComponent(document.getElementById('phone').value||'-')}`;if(WHATSAPP_NUMBER)window.open('https://wa.me/'+WHATSAPP_NUMBER+'?text='+msg,'_blank');else alert('Teklif akışı hazır. Telefon/WhatsApp numarası eklendiğinde bu talep doğrudan WhatsApp’a gönderilecek.')}

function socialPlaceholder(e,name){e.preventDefault();alert(name+' hesabı henüz açılmadı. Hesap açıldığında bağlantısı buraya eklenecek.')}
function phonePlaceholder(){alert('Telefon numarası henüz alınmadı. Numara geldiğinde bu buton aranabilir hale getirilecek.')}

function openMap(target){mapTarget=target;pickedLatLng=null;document.getElementById('mapStatus').textContent='';document.getElementById('mapModal').classList.add('show');setTimeout(()=>{if(!map){map=L.map('map').setView([36.8969,30.7133],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);map.on('click',e=>setMapPoint(e.latlng))}map.invalidateSize();},100)}
function setMapPoint(latlng){pickedLatLng=latlng;if(marker)marker.setLatLng(latlng);else marker=L.marker(latlng).addTo(map);document.getElementById('mapStatus').textContent=`Seçilen konum: ${latlng.lat.toFixed(6)}, ${latlng.lng.toFixed(6)}`}
function useMyLocation(){if(!navigator.geolocation){alert('Tarayıcınız konum özelliğini desteklemiyor.');return}navigator.geolocation.getCurrentPosition(pos=>{const ll=[pos.coords.latitude,pos.coords.longitude];map.setView(ll,16);setMapPoint({lat:ll[0],lng:ll[1]})},()=>alert('Konum alınamadı. Haritadan noktaya tıklayabilirsiniz.'))}
async function confirmMapLocation(){if(!pickedLatLng){alert('Lütfen haritada bir nokta seçin.');return}const lat=pickedLatLng.lat,lng=pickedLatLng.lng;let label=`Harita konumu: ${lat.toFixed(6)}, ${lng.toFixed(6)}`;try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${lat}&lon=${lng}&accept-language=tr`);if(r.ok){const d=await r.json();if(d.display_name)label=d.display_name}}catch(e){}document.getElementById(mapTarget+'Address').value=label;closeMap()}
function closeMap(){document.getElementById('mapModal').classList.remove('show')}
